### ISSUE TITLE
Small Issue with Length

### ISSUE THREAD

**Issue by archierosenblum** [mathemads/nexusadspy#16]
Hi George,

Love the API and it's a big help.  I noticed that when doing GET with 'publisher' it sits in a loop.  The return count in my case is 4.  I see that "res" is appended as "res[output_term]" but the condition to exit looks at "len(res)" which is always 1.  Should it be len(res[output_term))?

Sincerely, Archie

**Comment by waltherg** [comment]
Hi Archie,

thank you very much for your feedback. We fixed this issue on the `devel` branch the other doing exactly what you suggested.
We will create a new release so that you can `pip install` the fixed version.
Best,
Georg

**Comment by waltherg** [comment]
We are still improving the code on the `devel` branch before our next release. In the meantime you can also `pip install` nexusadspy directly from `devel` like so:

`pip install -e git+https://github.com/mathemads/nexusadspy.git@devel#egg=nexusadspy`

**Comment by archierosenblum** [comment]
Thank you very much!
